### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by sebre2211** [OpenXE-org/OpenXE#144]
Hello,
maybe you can help me.
If i run the setup.php using my browser, page 1 works.
But by clicking further to process with step 2, i receive:
 Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, string given in C:\xampp\htdocs\XentralR\XentralOpenSource-master\www\setup\setup.php:309 Stack trace: #0 C:\xampp\htdocs\XentralR\XentralOpenSource-master\www\setup\setup.php(96): GenerateHtml('2', Array) #1 {main} thrown in C:\xampp\htdocs\XentralR\XentralOpenSource-master\www\setup\setup.php on line 309

Maybe you know how to solve this issue?

THX ;-)

**Comment by OpenXE-ERP** [comment]
XentralOpenSource ist totally outdated, please use the latest OpenXE master branch.
