### ISSUE TITLE
Service "ArticleService" was not found.

### ISSUE THREAD

**Issue by am1github** [OpenXE-org/OpenXE#149]
Updated yesterday to latest git 1.11 (d5120a92).

Opening article section ( /index.php?module=artikel&action=list&top= ) points to an unexpected error:

> Xentral \ Core \ DependencyInjection \ Exception \ ServiceNotFoundException
> 
> Service "ArticleService" was not found.
> ../classes/Core/DependencyInjection/ServiceRegistry.php:73
> 
> 4. Xentral\Core\DependencyInjection\ServiceRegistry→get()
> ../classes/Core/DependencyInjection/ServiceContainer.php:35
> 
> 3. Xentral\Core\DependencyInjection\ServiceContainer→get()
> ../www/pages/artikel.php:1897
> 
> 2. Artikel→__construct()
> ../phpwf/class.player.php:276
> 
> 1. Player→Run()
> ../www/index.php:62

Second issue, maybe related, when adding positions to offer, order, invoice, ... the article could be selected but the form is not filled with data. Autocomplete seems not working.

**Comment by OpenXE-ERP** [comment]
Delete cache_services.php in folder userdata/tmp/YOURDATABASENAME/ or do the upgrade again, the newest version does the cleanup automatically.
