### ISSUE TITLE
Is it available in English

### ISSUE THREAD

**Issue by ugintl** [OpenXE-org/OpenXE#19]
Is it available in English?

**Comment by OpenXE-ERP** [comment]
Basically yes. The english translations are there but at the moment the translator is deactivated.
Work in progress will be tracked here: https://github.com/xenomporio-org/Xenomporio/issues/12

**Comment by ugintl** [comment]
@xenomporio What it means when you say "based on xentral"? Will it not work without xentral?

**Comment by OpenXE-ERP** [comment]
@ugintl Xenomporio is a fork of Xentral Open Source 20.3. As this, it is a standalone application that will run on it's own. (On Php8 and MariaDB)

**Comment by ugintl** [comment]
@xenomporio Thanks. Hope to get the English translation soon.

**Comment by OpenXE-ERP** [comment]
@ugintl Translation is no high priority at the moment. You could help if you like ;-)

**Comment by ugintl** [comment]
@xenomporio How can I help?

**Comment by OpenXE-ERP** [comment]
@ugintl 

Right now we figured out that there is a file with 3.500 translations [variablen.php](https://github.com/xenomporio-org/Xenomporio/blob/master/languages/englisch/variablen.php)  When comparing with the enterprise version, these are all the translations used for the frontend.  Problem is, the code which does the translation is missing or at least deactivated.

The first step would be to get this running again, and from there to add/fix additional translations.

**Comment by OpenXE-ERP** [comment]
Will not be implemented
