### ISSUE TITLE
Label-Manager

### ISSUE THREAD

**Issue by OpenXE-ERP** [OpenXE-org/OpenXE#21]
Labels are inserted via javascript, but depending on settings in the database. E.g. adresse list.

Investigate further...

index.php?module=ajax&action=labels&cmd=list
classes/Modules/Label/LabelGateway.php

**Comment by 0xAF7** [comment]
The file `www/pages/datalabels.php` contains the "Label Management UI". (Access via index.php?module=datalabels&action=list)

**Comment by OpenXE-ERP** [comment]
Can be fixed by the following INSERT statement in the database:

INSERT INTO `hook` (`name`, `aktiv`, `parametercount`, `alias`, `description`) VALUES
('parseuservars', 1, 0, '', ''),
('dokumentsend_ende', 1, 0, '', ''),
('auftrag_versand_ende', 1, 0, '', ''),
('transfer_document_incoming', 1, 0, '', '')
;

INSERT INTO `hook_register` (`hook_action`, `function`, `aktiv`, `position`, `hook`, `module`, `module_parameter`) VALUES
(0, 'DataTableLabelsInclude', 1, 3, (SELECT id FROM hook WHERE name = 'eproosystem_ende'), 'Datatablelabels', 0),
(0, 'DatatablelabelsParseUserVars', 1, 2, (SELECT id FROM hook WHERE name = 'parseuservars'), 'Datatablelabels', 0),
(0, 'DataTableLabelsDokumentSendHook', 1, 1, (SELECT id FROM hook WHERE name = 'dokumentsend_ende'), 'Datatablelabels', 0),
(0, 'DatatablelabelsOrderSent', 1, 1, (SELECT id FROM hook WHERE name = 'auftrag_versand_ende'), 'Datatablelabels', 0),
(0, 'DatatablelabelsTransferDocumentIncomming', 1, 1, (SELECT id FROM hook WHERE name = 'transfer_document_incoming'), 'Datatablelabels', 0);

**Comment by OpenXE-ERP** [comment]
f84e7af78a1e80c68cf1ea7b7824f811d571cfb0
