### ISSUE TITLE
git throws "error: invalid path" on windows for file "www/pages/content/rahmen70red_ohne_form.tpl:w"

### ISSUE THREAD

**Issue by rrusch** [OpenXE-org/OpenXE#22]
It looks like the part ":w" of the file name was introduced in error.

**Comment by OpenXE-ERP** [comment]
Thanks, I removed the wrongly named file in the latest commit.

By the way, you are welcomed to join our new community "openXE.org" for discussion of the project (it's in german).

**Comment by rrusch** [comment]
Thank you
