### ISSUE TITLE
Produktion module

### ISSUE THREAD

**Issue by OpenXE-ERP** [OpenXE-org/OpenXE#24]
Notes:

Produktion:

- mengeoriginal -> ?
- mengeaussschuss -> Quantity produced but scrap
- mengeerfolgreich -> Quantitiy produced -> Used in list display
- lager_ok etc. 0 - not, 1 - ok, 2 - partial

Produktion_position:

- stuecklistestufe = 1 -> Item to be produced
- stuecklistestufe = 0 -> Item to be consumed

- menge -> quantity planned
- geliefert_menge -> quantity produced (including scrap) / consumed

Lager_bewegung:
- Log for production / consumption (used in abschluss page)

Process:

- Plan quantities (stueckliste*quantity)
- Wait for stock available
- Reserve stock
- Do production (produced quantity, scrap quantity)
  - Optionally modify consumption
  - Remove consumed items from stock (according to production quantity and consumption recipe), reduce reservations
  - Put produced items in stock (production quantity, scrap quantity)
- Close production, free remaining reservations

Status:
- angelegt
- freigegeben
- gestartet
- abgeschlossen
- storniert

Movement of parts possible through erpapi?
function LieferscheinAuslagern($lieferschein,$anzeige_lagerplaetze_in_lieferschein=false, $standardlager = 0, $belegtyp = 'lieferschein', $chargenmhdnachprojekt = 0, $forceseriennummerngeliefertsetzen = false,$nurrestmenge = false, $lager_platz_vpe = 0, $lpiid = 0)

belegtyp === 'produktion' omits the first item in the itemlist (same as stuecklistestufe = 1?)
nurrestmenge = true -> menge_x = menge - menge_geliefert

function LagerEinlagern($artikel,$menge,$regal,$projekt,$grund="",$importer="",$paketannahme="",$doctype = "", $doctypeid = 0, $vpeid = 0, $permanenteinventur = 0, $adresse = 0)

Check:
function LagerFreieMenge($artikel, $mitautolagersperre = false, $standardlager = 0, $projektlager = 0)

**Comment by 0xAF7** [comment]
Do we also want to support Best before, Batches and Serial number for the first version? If so, we have to use other erpapi functions to correctly handle those cases

**Comment by 0xAF7** [comment]
(correct stock management especially in combination with batches etc. seem to be a big pain point of the code base as of now - maybe this could be one of the first areas where we introduce a new, openxe-specific implementation?)

**Comment by OpenXE-ERP** [comment]
Right now a minimum version is sufficient (stueckliste -> plan quantity -> stock booking partial or full quantity). We need a working version by end of the year because we are migrating after DEC 2022.

erpapi is hell, but right now I do not want to change too much in the original codebase.

I suggest to rework the erpapi at a later time, because this will need a lot of work on the software architecture beforehand.

**Comment by 0xAF7** [comment]
Agreed; We should focus on quickly getting the most important features working.

For the very first version: Do you think we even need the production position gui? We could also just do a very basic UI where you can select an item, a source and a target warehouse and a production quantity. Then you would push a button and the items (from the item's parts list) would be removed from the source warehouse and the amount of finished items would be added to the target warehouse.

**Comment by OpenXE-ERP** [comment]
Probably it's ok to have the simplest UI. I would like to have at least a position view to check for missing items in stock. Maybe read only is ok.

(I already started the position GUI)

**Comment by OpenXE-ERP** [comment]
A first simple implementation:

![produktion_draft1](https://user-images.githubusercontent.com/83282423/198043252-73b4122e-2a22-478e-83cf-73facca2aac8.png)

**Comment by 0xAF7** [comment]
Looks promising! 
I'm currently trying to reuse the standard "position" view to also be able to do stuff like sorting etc.

We should also probably figure out if we should use the _gen folder to somehow automatically generate the boilerplate code for some new modules. Im working on that rn.

**Comment by OpenXE-ERP** [comment]
I have seen the _gen files but did not understand yet the purpose.

Have a look at tools/module_creator. I am using this to create skeleton modules from an SQL table.

**Comment by OpenXE-ERP** [comment]
Use of erpapi functions was not satisfactory, made new implementations for:

- function ArtikelReservieren(int $artikel, $lager, int $menge_reservieren, string $objekt, int $objekt_id, int $position_id, string $text) : int
- function LagerCheckProduktion(int $produktion_id, int $lager) : int

Could be reused in erpapi or later in restructured API

**Comment by OpenXE-ERP** [comment]
@0xAF7 First working version of the production module is now checked in on master branch.

Any feedback is much appreciated...

**Comment by OpenXE-ERP** [comment]
Give target stock as form on produce

**Comment by OpenXE-ERP** [comment]
Release candidate now checked in on master branch

**Comment by OpenXE-ERP** [comment]
461b262e168928640897e1bb7341c3548bbf28a7
