### ISSUE TITLE
Installation Bug?

### ISSUE THREAD

**Issue by gitekDev** [OpenXE-org/OpenXE#78]
Vorgang = 
ZIP hochgeladen
Entpackt
Installation durchgeführt  -- > falsche Daten "mysql" eingegeben (Error)
zurück gegangen - richtige Daten eingepflegt 

Jetzt kann ich Pfad für Dateien nicht bestätigen. 
![openxeinsta](https://github.com/OpenXE-org/OpenXE/assets/93274163/0fbc73b9-9d0e-4f92-8b77-de5afe51c5e3)

**Comment by OpenXE-ERP** [comment]
Wenn Du im Ordner "conf" die "user.inc.php" löschst, wird das Setup von vorne gestartet, probiere das mal bitte.

**Comment by gitekDev** [comment]
Die user.inc.php ist nicht vorhanden(vermute mal das die Installation nicht abgeschlossen werden kann), ich kann immer wieder zurück zur Installation und bleibe wie auf dem Bild stehen. 

Fehler gefunden, ohne SSL geht es nicht. 
Hab fix ein SSL draufgebügelt und jetzt kann ich auch weiter.
