### ISSUE TITLE
Positions-Menge wird immer auf mindestens 1 aufgerundet

### ISSUE THREAD

**Issue by rrusch** [OpenXE-org/OpenXE#91]
Wenn ich eine Position in einem Auftrag erfasse und als Menge 0.5 eingebe, wird das auf 1 aufgerundet. gebe ich 1.5 ein, wird es richtig übernommen.
Der Fehler ist im JS vom Template zu finden (PR folgt). Mir ist nicht klar, wieso eine Menge < 1 zu 1 geändert werden sollte. Einigermassen logisch ist, wenn <=0 zu 1 geändert wird.

IMHO sollte auch eine negative Menge möglich sein. Aber das lasse ich jetzt mal weg, damit das ganze "minimalinvasiv" bleibt.

![image](https://github.com/OpenXE-org/OpenXE/assets/8038726/29544ade-e5f7-48c2-8a26-408020f1cd8f)

Wenn ich dann Tab drücke, wird die Menge in 1 geändert:
![image](https://github.com/OpenXE-org/OpenXE/assets/8038726/a1501315-8f05-43b0-9bc3-ad8eb3478165)

**Comment by rrusch** [comment]
Nach der Änderung im Template kann zwar eine Menge <1 eingegeben werden, aber nach Klick auf "einfügen" wird die Menge auf ganze Zahlen gerundet.

![image](https://github.com/OpenXE-org/OpenXE/assets/8038726/3f578970-bd44-4856-92e4-5819a971e119)

Nach einfügen:
![image](https://github.com/OpenXE-org/OpenXE/assets/8038726/c730551e-8f96-4898-8cd8-24e226d70fc0)

Die PDF-Vorschau zeigt es richtig an:
![image](https://github.com/OpenXE-org/OpenXE/assets/8038726/a6975761-09e6-49aa-a4ae-5fa2ec722384)


Gleiches Verhalten auch bei schreibgeschützten Dokumenten.

**Comment by rrusch** [comment]
Alle Abfragen in `class.yui.php` runden die Menge mittels `round(b.menge) as menge`. Ersetze das durch `trim(b.menge)+0 as menge`.

**Comment by OpenXE-ERP** [comment]
Ich habe 2 Anmerkungen:

- Die Menge sollte auch in der Datenbank ganzzahlig sein, selbst beim Abrunden gibt es ja am Ende eine Abweichung von Positionstabelle zu PDF
- Die MYSQL-Funktion zum Abrunden ist "FLOOR" (TRIM ist eine String-Funktion)

Ich denke wir sollten das Verhalten nur im Javascript ändern, also dort abrunden und dann den ganzzahligen Wert in die Datenbank legen.

Was denkst Du?

VG
Alex

**Comment by rrusch** [comment]
Hi Alex

Meiner Meinung nach, sollte die Menge in der Datenbank eben nicht zwingend ganzzahlig sein. Und darum auch nicht gerundet werden (weder auf- noch ab, noch kaufmännisch).
Mein PR adressiert zwei unterschiedliche Probleme im Zusammenhang mit der Menge:
1. Im JS: Jede Menge kleiner als 1 wird zu 1. Das ist für mich völlig unlogisch. Wieso sollte 1.2 möglich sein, 0.2 aber nicht?
2. Die Queries im File `class.yui.php` runden die Menge mit der ROUND Funktion. Ebenfalls nicht nachvollziehbar, wieso das so sein soll. Damit aber nun die Menge nicht als String zurückgegeben wird, wandle ich sie mit TRIM()+0 in eine Float um.

**Comment by OpenXE-ERP** [comment]
Das Verhalten ist auch nicht einheitlich. Zahlen unter 1 werden beim Einfügen als 1 abgelegt. Danach kann man aber z.B. 0.5 eingeben und das wird dann als 0.5 abgelegt. Zahlen über 1 werden immer abgelegt wie eingegeben aber gerundet angezeigt.

Man müsste sich zuerst grundsätzlich entscheiden ob Mengen ganzzahlig sein sollen oder nicht. Mein Vorschlag ist wir ändern das so ab, dass Zahlen immer ganzzahlig abgelegt werden, weil offensichtlich war das ja so gedacht. Ich habe die Befürchtung dass das Ablegen von nicht-ganzzahligen Werten irgendwo schlimme Probleme verursacht.

Logisch finde ich: negative Zahlen gehen nicht, alles andere wird gerundet. Ich vermute dass alles < 1 zu eins wird weil eine Menge 0 ja keinen Sinn ergibt.

Ändern würde ich das eher in der class.yui.php bei Zeile 571 und 2168 vor dem Speichern in die Datenbank...

Der gesamte Code zu der Funktion ist ja GRUSELIG

**Comment by rrusch** [comment]
Ich bin mit der ersten und der letzten Aussage voll einverstanden.

Dass Mengen in der Datenbank ganzzahlig sein sollen, ist für mich nicht offensichtlich. Offensichtlich ist für mich genau das Gegenteil der Fall:
 * Die entsprechende Spalte ist vom Typ DECIMAL(14,4)
 * Beim Speichern wird die Menge explizit in ein float verwandelt
 * Die Funktion `\erpAPI::FormatMenge()` in der Version vom 21.5.2021 gibt die DECIMAL(14,4) als float zurück
 * Im PDF wird korrekt gerechnet und angezeigt
Ausserdem ist es für ein ERP sehr untypisch, eine solche Beschränkung zu haben. Wie erfasst du Meterware? Wie Arbeitsstunden?

Über Null-Mengen oder sogar negative Mengen kann man streiten. Grundsätzlich sind Geschäftsfälle denkbar, bei denen Null oder Negative Mengen vorkommen können. Das würde ich aber jetzt bewusst nicht zulassen (und habe ich in meinem PR auch nicht), weil wir damit den offensichtlichen Denkansatz der ursprünglichen Entwickler verlassen.

Ich habe das Gefühl, dass man den "Positions-Editor" von irgendwo übernommen hat und so auch die Klasse vom YUI Framework irgendwie einbauen musste. Die Verwendung der ROUND Funktion ist untypisch, schliesslich gibt es die `\erpAPI::FormatMenge()` Funktion. Diese wurde mit dem Commit ad3207d6 von 8 Dezimalstellen auf 0 Dezimalstellen und zuvor mit dem Commit aff5eef9 von `TRIM()+0` auf `FORMAT()` geändert. Und so wurde auch diese Funktion zu einer Rundungsfunktion, was sie aber vorher nicht war. Wir haben das bisher noch gar nicht bemerkt, aber die Stücklisten sind jetzt jedenfalls falsch (siehe Issue #93).

Der Entscheid, nur noch ganzzahlige Mengen in der DB zu speichern, wäre für mich ein krasser breaking change. Wir könnten mit OpenXE so nicht ohne grösseren Aufwand weiterarbeiten.

Wer fällt den Grundsatzentscheid?

**Comment by OpenXE-ERP** [comment]
Aber dann wird doch genau andersherum ein Schuh draus: Mengen sind mit bis zu 4 Nachkommastellen möglich, aber die Maske gibt das nicht her und die Rundung ist falsch.

Ich würde daher eher die Masken erweitern sodass Nachkommastellen möglich sind, ggf. macht man das noch parametrierbar über die Firmendaten.

Die FormatMenge ist eine Funktion für die reine Anzeige von Werten nicht zum Bearbeiten. Ursprünglich war das TRIM()+0, ich hatte das erweitert und die Locale hinzugefügt, hardcoded erstmal DE. Jetzt müsste man das für Euch ja aber auch als Parameter machen weil in CH ist die Anzeige ja anders.

Grundsätzlich müssen die Masken aber direkt mit den Datenbankwerten geladen werden also weder gerundet noch formatiert.

**Comment by rrusch** [comment]
> Ich würde daher eher die Masken erweitern sodass Nachkommastellen möglich sind, ggf. macht man das noch parametrierbar über die Firmendaten.

Wie meinst du das mit dem erweitern? Müsste man das in ein anderes Issue auslagern?

> Die FormatMenge ist eine Funktion für die reine Anzeige von Werten nicht zum Bearbeiten. Ursprünglich war das TRIM()+0, ich hatte das erweitert und die Locale hinzugefügt, hardcoded erstmal DE. Jetzt müsste man das für Euch ja aber auch als Parameter machen weil in CH ist die Anzeige ja anders.

Genau. Stimmt aber so nicht ganz. Die Funktion füllt z.B. auch das Mengen-Feld, wenn ich eine Stücklisten-Position bearbeite. Und wenn nun das Tausender-Trennzeichen (dank FORMAT) vorkommt, wird die Zahl nachher falsch abgespeichert.

> Grundsätzlich müssen die Masken aber direkt mit den Datenbankwerten geladen werden also weder gerundet noch formatiert.

Das werden sie doch mit meinem PR, oder nicht?


Kurz zusammengefasst:

Wir verzetteln uns hier.
Wir bräuchten eine Einstellung für die Locale auf User-Basis. Dann bräuchten wir Input-Parser und Output-Formatter. Oder wir machen das mit einer JS-Library clientseitig. Mein Favorit ist aber der PHP NumberFormatter, also Serverseitig. Und nur im äussersten Notfall in der Datenbankabfrage.
Das kriegen wir aber nicht mit einem einfachen PR hin.

Und jetzt die Gretchenfrage:
Was muss am PR geändert werden, damit dieser gemerged werden kann?

**Comment by rrusch** [comment]
Ich könnte den PR #92 so ändern, dass nur das JS angepasst wird und die Formatierung der Menge lösen wir im Issue #32.
Was meinst du?

**Comment by rrusch** [comment]
Sorry, habe es mir anders überlegt. Ich denke kurzfristig ist der PR #92 unverändert die beste Lösung.

**Comment by OpenXE-ERP** [comment]
Ich habe jetzt nochmal geforscht, dieser Bug wurde schonmal bearbeitet im https://github.com/OpenXE-org/OpenXE/commit/6fc74f1bf353d78b199cc97549a91cea2083d40c. Dort war genau das Problem dass man keine Zahlen über 1000 eingeben konnte weil das Tausenderzeichen dann als Komma wieder eingelesen wurde.

Das richtig sauber zu kriegen wird knifflig. Wahrscheinlich ist es am Besten die Formulare als Zahlenfelder umzusetzen, dann kann der Browser sich um die Locale kümmern. Das habe ich z.B. im Produktionsmodul so umgesetzt. -> das wäre dann Issue #32 

Ich ziehe den PR jetzt rein.

Im PDF wird das Komma als Punkt ausgegeben, das sollte man noch anpassen damit es zumindest einheitlich ist.

**Comment by rrusch** [comment]
Danke.
Mit den Zahlenfeldern habe ich bisher keine guten Erfahrungen gemacht. Ausserdem ist es nur ein halbe Lösung, weil du ja trotzdem noch Zahlen in PDFs und als reines HTML zu formatieren hast.

Da wir in der Schweiz so ziemlich extrem sind mit 4 Landessprachen und unterschiedlichen Zahlenformaten, habe ich sowas hier rumliegen. Ich schaue mal, wie sich das adaptieren lässt.

Weiteres im Issue #32.
