### ISSUE TITLE
Mengen in Stücklisten werden jetzt gerundet, wurden sie in Xentral 20.3 aber nicht

### ISSUE THREAD

**Issue by rrusch** [OpenXE-org/OpenXE#93]

**Comment by rrusch** [comment]
Das kommt von der aktuellen Implementation der Funktion `\erpAPI::FormatMenge()`. Durch die Verwendung von `$decimals=0` wird die Menge auf ganze Zahlen gerundet.

**Comment by rrusch** [comment]
Siehe auch #32

**Comment by OpenXE-ERP** [comment]
https://github.com/OpenXE-org/OpenXE/commit/a9f3292f8f98ca37b7a42c9509e14942d6d605fb

**Comment by rrusch** [comment]
Ich denke, das kann nur gesamthaft befriedigend gelöst werden. Siehe auch Issue #32 und #91.
