### ISSUE TITLE
Ist die Menge in einer Stückliste >= 1000, verursacht das Tausendertrennzeichen Probleme

### ISSUE THREAD

**Issue by rrusch** [OpenXE-org/OpenXE#94]

**Comment by rrusch** [comment]
Das Tausendertrennzeichen wird als Dezimaltrennzeichen interpretiert und die Zahl wird entsprechend abgeschnitten in die Datenbank gespeichert.

Siehe auch #32

**Comment by OpenXE-ERP** [comment]
https://github.com/OpenXE-org/OpenXE/commit/a9f3292f8f98ca37b7a42c9509e14942d6d605fb
