### ISSUE TITLE
Bug: Zugriffskonfiguration (htaccess) fehlerhaft.

### ISSUE THREAD

**Issue by Diralytic** [OpenXE-org/OpenXE#97]
Hallo!

Nachdem ich erfolgreich die Db von Xentral migriert habe und danach upgrade.php benutzt habe, habe ich folgendes Problem am Login-Screen:

`Achtung: Zugriffskonfiguration (htaccess) fehlerhaft. Bitte wenden Sie sich an Ihren an Ihren Administrator.
(htaccess nicht aktiv.)`

htaccess Inhalt:
```
# Generated file from class.acl.php
# For detection of htaccess functionality
SetEnv OPENXE_HTACCESS on
# Disable directory browsing 
Options -Indexes
# Set default page to index.php
DirectoryIndex "index.php"
# Deny general access
Order deny,allow
<FilesMatch ".">
    Order Allow,Deny
    Deny from all
</FilesMatch>
# Allow index.php
<Files "index.php">
    Order Allow,Deny
    Allow from all
</Files>
# end
```

Version: V.1.10 (a9f3292f)

**Comment by OpenXE-ERP** [comment]
Auf welchem Webserver läuft OpenXE? (Wir unterstützen nur Apache2 mit php als Modul.)

Bitte die .htaccess-Einstellungen überprüfen, es muss im Server aktiviert sein.

Schau mal bitte hier nach, Abschnitt 4 etc.:

https://openxe.org/wiki/index.php?entry/4-installation-rhel-rockylinux-centos/

**Comment by Diralytic** [comment]
Hallo! Habe apache2 und php 8.1 mit den empfohlenen Einstellungen.
Habe nun openxe als "master" runter geladen anstatt die v1.10 und da tritt der Fehler nicht mehr auf.
Danke für die Hilfe!
