### ISSUE TITLE
Bug: Login Logo nach upgrade fehlerhaft

### ISSUE THREAD

**Issue by Diralytic** [OpenXE-org/OpenXE#98]
Hallo!

Nach dem Upgrade von Xentral auf OpenXE habe ich das Problem, dass das Logo fehlerhaft ist:

![image](https://github.com/OpenXE-org/OpenXE/assets/28673178/c2774eae-686a-43c6-be37-b40450973622)

Habe schon versucht in den Grundeinstellungen das Bild zu ändern aber es ändert sich nichts.

Version: V.1.10 (a9f3292f) 

Vielen Dank!

**Comment by OpenXE-ERP** [comment]
Führe mal bitte das hier in der Datenbank aus:

`update firmendaten_werte set wert = 0 where name = 'firmenlogoaktiv';`

**Comment by Diralytic** [comment]
Vielen Dank - funktioniert!
